AWS_ACCESS_KEY_ID = "AKIAIOSFODNN7EXAMPLE"
GITHUB_TOKEN = "ghp_TESTONLY1234567890ABCDEF"
PRIVATE_KEY = """-----BEGIN RSA PRIVATE KEY-----
TESTONLYFAKEKEYDATA1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ
-----END RSA PRIVATE KEY-----"""
GITHUB_FINE_GRAINED_TOKEN = "github_pat_TESTONLY1234567890ABCDEFGHIJK"
OPENSSH_PRIVATE_KEY = """-----BEGIN OPENSSH PRIVATE KEY-----
TESTONLYFAKEOPENSSHKEYDATA1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ
-----END OPENSSH PRIVATE KEY-----"""
JWT_TOKEN = "eyJFAKEHEADER123.eyJFAKEPAYLOAD456.FAKESIGNATURE789"