name: Secret Scanner

on:
  pull_request:
  push:
    branches: [main]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run secret scan
        run: |
          python cli.py scan cli.py
          python cli.py scan scanner.py
          python cli.py scan config.py
          python cli.py scan staged_files.py
          python cli.py scan pre_commit_hook.py
          python cli.py scan install_hook.py